export const MESSAGE = Object.freeze({
  PLAYER_REPORT: 'dualCaptions.player.report',
  PLAYER_DISCOVER: 'dualCaptions.player.discover',
  PLAYER_GET: 'dualCaptions.player.get',
  PLAYER_SELECT: 'dualCaptions.player.select',
  STATE_GET: 'dualCaptions.state.get',
  STATE_PATCH: 'dualCaptions.state.patch',
  TRACK_ADD: 'dualCaptions.track.add',
  TRACK_UPSERT_LOCAL: 'dualCaptions.track.upsertLocal',
  TRACK_CACHE_BUILTIN: 'dualCaptions.track.cacheBuiltin',
  TRACK_REMOVE: 'dualCaptions.track.remove',
  TRACK_OFFSET: 'dualCaptions.track.offset',
  TRACK_TIMING: 'dualCaptions.track.timing',
  AI_CONFIG_GET: 'dualCaptions.ai.get',
  AI_CONFIG_PATCH: 'dualCaptions.ai.patch',
  AI_MODELS_GET: 'dualCaptions.ai.models.get',
  CAPTION_TRANSLATE: 'dualCaptions.caption.translate',
  WORDS_LIST: 'dualCaptions.words.list',
  WORDS_SAVE: 'dualCaptions.words.save',
  WORD_EXPLAIN: 'dualCaptions.words.explain',
  WORD_TRANSLATE: 'dualCaptions.words.translate',
  SENTENCES_LIST: 'dualCaptions.sentences.list',
  SENTENCES_SAVE: 'dualCaptions.sentences.save',
  SENTENCE_EXPLAIN: 'dualCaptions.sentences.explain',
  SPEECH_SETTINGS_GET: 'dualCaptions.speech.settings.get',
  SPEECH_SETTINGS_PATCH: 'dualCaptions.speech.settings.patch',
  SPEECH_SPEAK: 'dualCaptions.speech.speak',
  LOCAL_SUBTITLE_EXISTING: 'dualCaptions.localSubtitle.existing',
  LOCAL_SUBTITLE_GENERATE: 'dualCaptions.localSubtitle.generate',
  LOCAL_SUBTITLE_STATUS: 'dualCaptions.localSubtitle.status',
  CONTENT_FULL_STATE: 'dualCaptions.content.fullState',
  CONTENT_SETTINGS: 'dualCaptions.content.settings',
  CONTENT_TRACKS: 'dualCaptions.content.tracks',
  CONTENT_POSITION_PATCH: 'dualCaptions.content.positionPatch',
  CONTENT_RESET: 'dualCaptions.content.reset',
  PANEL_STATE_GET: 'dualCaptions.panel.get',
  PANEL_STATE_PATCH: 'dualCaptions.panel.patch',
  PANEL_CONTEXT_GET: 'dualCaptions.panel.context',
  PANEL_TOGGLE: 'dualCaptions.panel.toggle',
  PANEL_SHOW: 'dualCaptions.panel.show',
});

export const ok = (data = {}) => ({ ok: true, data });
export const failure = (error) => ({ ok: false, error: error instanceof Error ? error.message : String(error) });
