#!/usr/bin/env python3
"""Generate host-sized Compose resource limits without starting any service."""
from __future__ import annotations

import argparse
import math
import json
import os
import subprocess
from pathlib import Path
import sys
import tempfile

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "local-server"))
from resource_budget import (ResourceCapacity, ResourceDetectionError, compute_budget, detect_host_resources,
                             detect_effective_resources)

DEFAULT_OUTPUT = ROOT / "compose.resources.local.yaml"


def detect_docker_resources() -> ResourceCapacity | None:
    """Read local Engine/VM capacity only; never launch Docker or a container.

    Remote contexts are rejected: sizing another machine from this host is unsafe.
    Missing/stopped Docker produces a visible warning, not guessed VM resources.
    """
    try:
        endpoint = os.environ.get("DOCKER_HOST", "")
        if os.environ.get("DOCKER_CONTEXT") or not endpoint:
            result = subprocess.run(
                ["docker", "context", "inspect", "--format", "{{json .Endpoints.docker.Host}}"],
                check=True, capture_output=True, text=True, timeout=5)
            endpoint = json.loads(result.stdout)
        if not isinstance(endpoint, str) or not endpoint.startswith(("unix://", "npipe://")):
            raise ValueError("Use a local Docker context (unix:// or npipe://), not a remote daemon")
        result = subprocess.run(["docker", "info", "--format", "{{json .}}"],
                                check=True, capture_output=True, text=True, timeout=5)
        info = json.loads(result.stdout)
        if info.get("OSType") != "linux":
            raise ValueError("Use a local Docker daemon in Linux-container mode")
        return ResourceCapacity(info["NCPU"], info["MemTotal"])
    except (OSError, subprocess.SubprocessError, json.JSONDecodeError,
            KeyError, TypeError, ResourceDetectionError):
        print("Warning: Docker VM resources not detected; using host/effective limits only. "
              "Rerun with Docker available before applying the override.", file=sys.stderr)
        return None


def render_override(budget) -> str:
    # Round down rather than exceeding the requested fraction during serialization.
    cpus = math.floor(budget.cpu_quota * 1_000_000) / 1_000_000
    if cpus < 0.01 or budget.memory_bytes < 6 * 1024**2:
        raise ValueError("Budget is below Docker's usable minimum (0.01 CPU / 6 MiB); "
                         "refusing to emit an unlimited or invalid resource setting")
    return (
        "# Generated by scripts/configure-resources.py; pass after compose.yaml with -f.\n"
        "services:\n  subtitles:\n"
        f'    cpus: "{cpus:.6f}"\n'
        f"    mem_limit: {budget.memory_bytes}\n"
        f"    memswap_limit: {budget.memory_bytes}\n"
        '    environment:\n      SUBSANYWHERE_RESOURCE_FRACTION: "1"\n'
        f'      OMP_NUM_THREADS: "{budget.threads}"\n'
        f'      MKL_NUM_THREADS: "{budget.threads}"\n'
    )


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--percent", type=float, default=100 / 3,
                        help="Percentage of host CPU/RAM (default: one third)")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--dry-run", action="store_true", help="Print YAML without writing a file")
    args = parser.parse_args(argv)
    if not 0 < args.percent <= 100:
        parser.error("--percent must be finite and 0 < percent <= 100")
    try:
        return _configure(args)
    except (ResourceDetectionError, ValueError, OSError) as error:
        print(f"Resource configuration failed: {error}", file=sys.stderr)
        return 1


def _configure(args) -> int:
    host = detect_host_resources()
    effective = detect_effective_resources(host)
    docker = detect_docker_resources()
    if docker is not None:
        effective = ResourceCapacity(min(effective.cpu_count, docker.cpu_count),
                                     min(effective.memory_bytes, docker.memory_bytes))
    budget = compute_budget(host, args.percent / 100, ceiling=effective)
    content = render_override(budget)
    if not args.dry_run:
        temporary = None
        try:
            with tempfile.NamedTemporaryFile(mode="w", encoding="utf-8", newline="\n",
                                             dir=args.output.parent, prefix=".resources-",
                                             suffix=".tmp", delete=False) as stream:
                temporary = Path(stream.name)
                stream.write(content)
            os.replace(temporary, args.output)
        finally:
            if temporary is not None:
                temporary.unlink(missing_ok=True)
        print(f"Wrote {args.output}. No services were changed.", file=sys.stderr)
    print(content, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
